name: Publish to pkg.pr.new

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Set version
        run: |
          VERSION=$(jq -r .version package.json)
          jq ".version = \"$VERSION.${{ github.run_number }}\"" package.json > package.json.tmp
          mv package.json.tmp package.json

      - name: Build
        run: pnpm build

      - run: pnpx pkg-pr-new publish
